### ISSUE TITLE
geometry error

### ISSUE THREAD

**Issue by wruwak** [giscan/Generalizer#14]
Hi, i'm totally green as programist, but really appreciate Your work. I've been using the plug for several years only to contours. I download asc file with DEM from LIDAR, create contours (default function in Raster menu in QGIS, alternatively in ArcMap) and try to improve them- Generalizer is really the only plug that gives good results.
There are two problems.
1. Doesn't work on latests editions of Qgis (maybe from 3.20?), especially 3.22.3 on my PC, but still works on 3.16 and (i'm not shure) on 3.18, (Unable to load plugin 'cartolinegen' due to an error calling its classFactory () method"- [unable to load.txt](https://github.com/giscan/Generalizer/files/8228175/unable.to.load.txt)
2. More complicated- on some cases it shows 'Can't generalize! Check geometry validity.' 2-3 Y ago it was on 2-3 cases to 10, but with newest DEMs (better quality, higher resolution) are more problematic... Looks like plug tries to create some contours (and create) and stops work on problematic place. File with result contains only part of the contours. I tried to find that geometry errors, on Qgis and Arc, but failed. Dont know where's the problem, what stops the process. I suspect a problem with Python too.
Can You help to resolve that ? How I can to add a samples (shp with contours before- 26 MB, after- 1,5 MB, DEM ~40MB)

[unable to load.txt](https://github.com/giscan/Generalizer/files/8228177/unable.to.load.txt)

**Comment by kikislater** [comment]
Hello,

Thank you for reporting but this is not the plugin available in this repository : from your 1 and 2 `unable to load.txt` we could see : 
"C:\Users/arepo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\**cartolinegen**\generalize.py"

The plugin which have error is available here : https://github.com/dtutic/CartoLineGen
The plugin available in this repository is this one =>  https://plugins.qgis.org/plugins/Generalizer3 

Btw, I have corrected the error and made a PR here : https://github.com/dtutic/CartoLineGen/pull/5
